### ISSUE TITLE
InvocationTargetException server crash

### ISSUE THREAD

**Issue by KydZombie** [DrParadox7/Lost-Era-Modpack#6]
Keep getting this error over and over again on starting a server:

`A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more`

**Comment by DrParadox7** [comment]
At first glance I would imagine you're running a OpenJDK Java version above 8, which is not compatible with Minecraft 1.7.10.
Please, always post the full logs as snippets are not very comprehensive for diagnosing issues.

**Comment by DrParadox7** [comment]
Looking at the stacktrace you've sent there should be some logs generated in the logs folder. That would be helpful.
Also, ServerStarter has its own log called `serverstarter.log` that will also be found at the server directory.

**Comment by KydZombie** [comment]
`serverstart.log` only seems to pertain to the downloading of the modpack, which worked fine. But I can post that anyway. `latest.log` doesn't actually even update if I use the non-working batch script (which goes through serverstart.jar), it just stays as the previous, working run of the game (with a batch script directly running the forge server jar).
[serverstarter.log](https://github.com/DrParadox7/Lost-Era-Modpack/files/7859934/serverstarter.log)

**Comment by KydZombie** [comment]
Sorry for the multiple comments by the way, not very used to big block messages like what I've been seeing other github users use (and I keep realizing things after the fact). This is exactly what gets output to the console on running it:
[consoleoutput.txt](https://github.com/DrParadox7/Lost-Era-Modpack/files/7859945/consoleoutput.txt)

**Comment by DrParadox7** [comment]
The more I look at it the more likely it seems it’s using the wrong Java as the error it show is the same as the one we get when user attempt to run with versions above 8.
In `server-setup-config.yaml` use the `forceJavaPath=` entry to make it use the directory of Java 8 installed in your system instead of whatever it’s finding. 
it’s all the way at the bottom.

This should fix it completely.

**Comment by DrParadox7** [comment]
If that still doesn’t work do post what you added to the entry above and I will personally fetch that Java version and attempt it to launch it myself

**Comment by DrParadox7** [comment]
Also, is there nothing on crash reports?

**Comment by DrParadox7** [comment]
Here:
![image](https://user-images.githubusercontent.com/47131096/149271739-bcc78d26-4430-469e-b5bd-8e7e0a74f47f.png)

I've replicated your same issue using Java 11.
If that's what you're experiencing than it is 1000% using something that isn't Java 8.

**Comment by KydZombie** [comment]
This fixed it. Thank you
