### ISSUE TITLE
Crash Report: java.lang.UnsatisfiedLinkError: no awt in java.library.path

### ISSUE THREAD

**Issue by BattleCh1cken** [DrParadox7/Lost-Era-Modpack#69]
### Your Pack Version

1.6.0

### Type of Instance

Multiplayer

### Your Actions

**OS Info:**
x86_64 Linux (NixOS)

**JAVA Info:**
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-ga)
OpenJDK 64-Bit Server VM (build 25.362-bga, mixed mode)

I used these commands to download and unzip the modpack:
```sh
wget https://cdn.modrinth.com/data/p87Jiw2q/versions/s0e5H7ng/LostEra_Modpack_1.6.0.mrpack
unzip LostEra_Modpack_1.6.0.mrpack
cd overrides
java -jar serverstarter-2.0.1.jar
```
It's highly likely that this issue is related to NixOS, I'll try to reproduce it on a FHS compliant OS soon.

### Crash Report

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/6/23 2:11 PM
Description: Exception in server tick loop

java.lang.UnsatisfiedLinkError: no awt in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        at java.lang.Runtime.loadLibrary0(Runtime.java:843)
        at java.lang.System.loadLibrary(System.java:1136)
        at java.awt.Toolkit$3.run(Toolkit.java:1636)
        at java.awt.Toolkit$3.run(Toolkit.java:1634)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
        at java.awt.Toolkit.<clinit>(Toolkit.java:1670)
        at sun.awt.AppContext$2.run(AppContext.java:277)
        at sun.awt.AppContext$2.run(AppContext.java:266)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.AppContext.initMainAppContext(AppContext.java:266)
        at sun.awt.AppContext.access$400(AppContext.java:135)
        at sun.awt.AppContext$3.run(AppContext.java:321)
        at sun.awt.AppContext$3.run(AppContext.java:304)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.AppContext.getAppContext(AppContext.java:303)
        at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:154)
        at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
        at net.minecraft.server.MinecraftServer.func_147138_a(MinecraftServer.java:506)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:394)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 6.3.9
        Java Version: 1.8.0_362, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 1953088512 bytes (1862 MB) / 2147483648 bytes (2048 MB) up to 4294967296 bytes (4096 MB)
        JVM Flags: 8 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx4G -Xms2G
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
        FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 3 mods loaded, 3 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHIJAAAA       mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
        UCHIJAAAA       FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar)
        UCHIJAAAA       Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar)
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Player Count: 0 / 20; []
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)%

### Final Checklist

- [X] I have provided all the required crash reports/logs.
- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by DrParadox7** [comment]
Doesn't seem like an issue caused by the pack itself.

I can help if you once you identify the problematic step between:
-Downloading the pack
-unzipping the pack
-Accessing the unzipped folder
-Running Server Starter

**Comment by BattleCh1cken** [comment]
I've tested this on Fedora, and it seems to work, so it must be an issue on my end.
