### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by ArchieA10** [DrParadox7/Lost-Era-Modpack#70]
### Your Pack Version

1.6.0

### Type of Instance

Single Player

### Your Actions

Crashes immediately upon launching using MultiMC. Generally shows that it crashes 1-2 seconds after clicking launch
<img width="346" alt="image" src="https://github.com/DrParadox7/Lost-Era-Modpack/assets/138900505/1471cc07-8e9e-4c36-90b4-38d2b5fb3201">

### Crash Report

Failed to start Minecraft:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).

### Final Checklist

- [X] I have provided all the required crash reports/logs.
- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by DrParadox7** [comment]
Provide the required crash report

**Comment by DrParadox7** [comment]
User is likely using Java 9 or above, which is not compatible with the pack.
