### ISSUE TITLE
Fails to launch in Modrinth App

### ISSUE THREAD

**Issue by CodeF53** [DrParadox7/Lost-Era-Modpack#74]
### Type of Instance

Single Player

### Installation Target

Your Own Computer or Laptop

### Your Actions

Attempting to install the modpack in [Modrinth App](https://modrinth.com/app) (modrinth's own launcher)

1. install Modrinth app https://modrinth.com/app
2. go through launcher onboarding (log in with microsoft account...)
3. search for and install pack
4. click play on the new instance.

### Your Pack Version

1.6.1

### Required Logs

No `logs` folder exists inside the instance's folder.

```
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
 

### Final Checklist

- [X] I have provided all the required logs.
- [X] I searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by DrParadox7** [comment]
Trying to run a modpack needing Java 8 on Java 9+.
